"""adiciona valor com desconto ao contrato de aluguel

Revision ID: 2b5d87fdff66
Revises: 91da9233cecd
Create Date: 2026-09-15 17:24:39.894633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5d87fdff66'
down_revision = '91da9233cecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_agreements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discounted_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_agreements', schema=None) as batch_op:
        batch_op.drop_column('discounted_amount')

    # ### end Alembic commands ###
