"""fines e renavam

Revision ID: 60a1e00e5863
Revises: 94785af5317d
Create Date: 2026-09-11 10:47:06.775891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a1e00e5863'
down_revision = '94785af5317d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('numero_ait', sa.String(length=30), nullable=False),
    sa.Column('extracted_data_infracao', sa.Date(), nullable=True),
    sa.Column('extracted_local', sa.String(length=255), nullable=True),
    sa.Column('extracted_descricao', sa.String(length=255), nullable=True),
    sa.Column('extracted_valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('extracted_vencimento', sa.Date(), nullable=True),
    sa.Column('extracted_pontos', sa.Integer(), nullable=True),
    sa.Column('extracted_orgao_status', sa.String(length=60), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('consulted_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('confirmed_vencimento', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id', 'numero_ait', name='uq_fine_car_ait')
    )
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renavam', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('renavam')

    op.drop_table('fines')
    # ### end Alembic commands ###
