"""adiciona chassi ao carro

Revision ID: 91da9233cecd
Revises: 60a1e00e5863
Create Date: 2026-09-11 16:38:20.278197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91da9233cecd'
down_revision = '60a1e00e5863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chassi', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('chassi')

    # ### end Alembic commands ###
