"""km com casas decimais no relatorio automatico de GPS

Revision ID: 94785af5317d
Revises: ff039bb88fb6
Create Date: 2026-08-18 10:50:53.867218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94785af5317d'
down_revision = 'ff039bb88fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.alter_column('current_km',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('gps_readings', schema=None) as batch_op:
        batch_op.alter_column('extracted_km',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('confirmed_km',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gps_readings', schema=None) as batch_op:
        batch_op.alter_column('confirmed_km',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('extracted_km',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.alter_column('current_km',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
