"""contas fixas, avulsos, projecao, confirmacao manual

Revision ID: ff039bb88fb6
Revises: 8e23a326c52b
Create Date: 2026-08-03 11:01:21.765299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff039bb88fb6'
down_revision = '8e23a326c52b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saldo_inicial', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('saldo_data', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_hoc_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurring_item_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recurring_item_id'], ['recurring_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recurring_item_id', 'due_date', name='uq_item_due_date')
    )
    with op.batch_alter_table('expected_charges', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('manually_confirmed', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column('confirmed_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(
            'fk_expected_charges_confirmed_by_user_id', 'users', ['confirmed_by_user_id'], ['id']
        )

    with op.batch_alter_table('rental_agreements', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('reliability_pct', sa.Integer(), nullable=False, server_default='100')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_agreements', schema=None) as batch_op:
        batch_op.drop_column('reliability_pct')

    with op.batch_alter_table('expected_charges', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expected_charges_confirmed_by_user_id', type_='foreignkey')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('confirmed_by_user_id')
        batch_op.drop_column('manually_confirmed')

    op.drop_table('recurring_occurrences')
    op.drop_table('recurring_items')
    op.drop_table('ad_hoc_entries')
    op.drop_table('cash_settings')
    # ### end Alembic commands ###
